# --------------------------------------------------
#   Population genetics simulator config file.
#   Edit the values below to change runtime behavior.
# --------------------------------------------------

# === Parameters used by program: fix_2_gene2.py === 
# Number of times to repeat each parameter set run, i.e., each so-called attempt.
# - More repetitions = better statistical averaging
# - Set to 1 for quick test runs, or to optime parallel processing on your computer
Repetitions: 10

# === Parameters used by program: fix_1_gene.py === 
# Maximum number of generations per simulation to prevent endless runs
# - Use small values (e.g. 1000) for testing or debugging
generations: 100000000

# Save detailed per-generation data? Options: true or false
# - WARNING: if true, can produce huge files!
# - Set to true if you plan to generate graph
document_results_every_generation: true


# === Parameters used by programs: ===
# create_plots_all_simul_1_haplo.py, create_plots_ave_simul_1_haplo.py
# Graphical displays can be generated in Powerpoint files or individual tiff files.
# Options for OUTPUT_TYPE: powerpoint, images, both. Spelling is case sensitive!
OUTPUT_TYPE: both